(library
 (public_name current_github)
 (libraries
  astring
  base64
  ca-certs
  cmdliner
  cohttp
  cohttp-eio
  cstruct
  current
  current.cache
  current_term
  current_git
  current_web
  digestif
  domain-name
  duration
  eio
  eio.unix
  github-unix
  lwt_eio
  ptime
  fmt
  logs
  mirage-crypto
  mirage-crypto-pk
  prometheus
  result
  rresult
  tls
  tls-eio
  uri
  x509
  tyxml
  unix
  tyxml.functor
  yojson)
 (preprocess
  (pps ppx_deriving_yojson)))
