(library
 (public_name current_github)
 (libraries
  astring
  base64
  cmdliner
  cohttp
  current
  current.cache
  current.http
  current_term
  current_git
  current_web
  digestif
  duration
  eio
  ptime
  fmt
  logs
  mirage-crypto-pk
  prometheus
  result
  rresult
  uri
  x509
  tyxml
  unix
  tyxml.functor
  yojson)
 (preprocess
  (pps ppx_deriving_yojson)))
