(rule
 (target static.ml)
 (deps
  (glob_files static/css/*)
  (glob_files static/img/*)
  (glob_files static/js/*))
 (action
  (run ocaml-crunch --silent --mode=plain --output=%{target} static)))

(library
 (public_name current_web)
 (libraries
  astring
  base64
  bos
  cmdliner
  cohttp-eio
  cstruct
  current
  current.cache
  current_term
  csv
  ansi
  eio
  eio.unix
  fmt
  fpath
  logs
  magic-mime
  mirage-crypto
  mirage-crypto-rng.unix
  multipart_form
  ppx_sexp_conv.runtime-lib
  prometheus
  prometheus-app
  re
  result
  routes
  session
  session-cohttp
  sexplib
  sqlite3
  tyxml
  tyxml.functor
  ppx_deriving_yojson.runtime
  unix
  yojson
  uri)
 (preprocess
  (pps ppx_deriving.std ppx_deriving_yojson)))
